apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ingress-annotation-test
  labels:
    app: ingress-annotation-test

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingress-annotation-test

  template:
    metadata:
      labels:
        app: ingress-annotation-test

    # Container Spec
    spec:
      containers:
        - name: ingress-annotation-test
          image: alicek106/ingress-annotation-test:print-proxy-origin-ip
          ports:
            - name: flask
              containerPort: 5000
          imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: ingress-annotation-test-svc

spec:
  ports:
    - name: web
      port: 80
      targetPort: flask
      nodePort: 30001

  selector:
    app: ingress-annotation-test

  type: NodePort
