apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ingress-annotation-test
  labels:
    app: ingress-annotation-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingress-annotation-test
  template:
    metadata:
      labels:
        app: ingress-annotation-test
    spec:
      containers:
      - name: ingress-annotation-test
        image: alicek106/ingress-annotation-test:timeout-test
        ports:
        - name: flask
          containerPort: 80
        imagePullPolicy: Always
        env:
        - name: SLEEP_INTERVAL
          value: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-annotation-test-svc
spec:
  ports:
  - name: web
    port: 80
    targetPort: flask
  selector:
    app: ingress-annotation-test
  type: ClusterIP
