apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ingress-annotation-test-spring
  labels:
    app: ingress-annotation-test-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-annotation-test-spring
  template:
    metadata:
      labels:
        app: ingress-annotation-test-spring
    spec:
      containers:
      - name: ingress-annotation-test-spring
        image: alicek106/ingress-annotation-test:spring-jaeger-properties
        ports:
        - name: web
          containerPort: 80
        imagePullPolicy: Always
        env:
        - name: CONF_JAEGER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CONF_JAEGER_PORT
          value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-annotation-test-spring-svc
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: ingress-annotation-test-spring
  type: ClusterIP

